name: update data

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: setup
        run: |
          sudo apt install aria2 osmium-tool pv
          pip install -r requirements.txt 

      - name: download latest changeset
        run: |
          wget -N https://planet.openstreetmap.org/planet/changesets-latest.osm.bz2.torrent
          aria2c --seed-time 0 --check-integrity changesets-latest.osm.bz2.torrent

      - name: save compressed changeset csv
        run: osmium cat --output-format opl $(ls *.osm.bz2) | python3 src/save_changesets_csv.py temp
      
      - name: save data
        run: python3 src/data_crunching_and_saving.py temp
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: assets/*
          commit-message: data update
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          delete-branch: true
          title: 'data update'
          body: 'update plots and tables with the latest changeset'
          
          
